### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by yong-chian**
added devise basic authentication page (registrations and sessions)

### CODE REVIEW

**Comment by Littlezealous** [comment]
Sign up and login in sessions working as per intended. 
Reset password and update details not working.

**Review by Littlezealous — APPROVED** [review]
LGTM

**Comment by yong-chian** [comment]
updated experiences_controller and views, installed pundit gem and authorisation for experiences' action.

**Comment by yong-chian** [comment]
> Sign up and login in sessions working as per intended. Reset password and update details not working.

will try to work on this tomorrow

**Pull request merged**
